---
- name: First Playbook
  hosts: lab1_all
  gather_facts: no
  connection: network_cli
  become: yes
  tasks:
     - name: disable domain-lookup
       ios_config:
        lines:
         - no ip domain-lookup

     - name: get the domain of devices
       cli_command:
        command: show run | i domain name
       register: result

     - debug: var=result.stdout_lines
