---
- name: Route Summary
  hosts: lab1_routers
  gather_facts: no
  connection: network_cli
  #become: yes
  tasks:
     - name: show interfaces
       cli_command:
        command: sh ip int br
       register: result
     - debug: var=result.stdout_lines

     - name: show routes
       cli_command:
        command: sh ip route | b Gateway
       register: result
     - debug: var=result.stdout_lines
